name: ElytraRework
version: '0.1.0'
main: org.vooogle.elytraRework.ElytraRework
api-version: '1.21'
load: STARTUP
authors: [ Vooogle ]
description: Elytra Reworked

commands:
  elytrarework:
    description: Main command for ElytraRework plugin
    usage: /elytrarework <reload>
    aliases: [er]
    subcommands:
      reload:
        description: Reloads the plugin configuration
        usage: /elytrarework reload